[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cuda_redist_lib"
version = "0.1.0"
authors = [{ name = "Connor Baker", email = "connorbaker@tweag.io" }]
requires-python = ">=3.12"
license = { text = "BSD-3-Clause" }
description = "Library of functions for NVIDIA's redistributable manifests"
dependencies = ["annotated-types", "pydantic", "rich"]

[project.optional-dependencies]
dev = ["ruff"]

[project.scripts]
regen-manifest-hashes = "cuda_redist_lib.cmd:regen_manifest_hashes.main"
mk-index-of-sha256-and-relative-path = "cuda_redist_lib.cmd:mk_index_of_sha256_and_relative_path.main"

[project.urls]
Homepage = "https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/python-modules/cuda-redist-lib"

[tool.ruff]
line-length = 120

[tool.ruff.format]
preview = true

[tool.ruff.lint]
preview = true
select = ["F", "E", "W", "I", "PL", "FURB", "LOG", "RUF", "G", "TID"]
ignore = [
  # Ignore functions with many arguments (I like currying)
  "PLR0913",
]

[tool.pyright]
include = ["./cuda_redist_lib"]
pythonVersion = "3.12"
pythonPlatform = "Linux"
typeCheckingMode = "strict"
