# Turns a checked-in sample manifest into a component's sample tests: one sample derivation per
# upstream project, one tester per executable, a sandboxed test per tester, and the manifest drift
# check.
#
# The result is the set of tests, and nothing else. A test carries its tester on `passthru.tester`,
# and the tester carries the compiled sample on `passthru.sample`, so both are still there to build
# or to debug -- but a set named for a component's tests holds tests, rather than a bundle of four
# kinds of thing filed under the name of one of them. It is marked `recurseIntoAttrs` so that
# whatever walks the package set finds those tests instead of stopping at an attribute which looks
# wired up and is not.
#
# Factored out because every component repeats the same wiring, and because a divergence between
# components in how testers are keyed or how requirements are attached is exactly the kind of thing
# that silently loses coverage.
#
# Called from `packages/tests/<component>-samples`, not from the component itself: a redistributable
# is unpacked rather than compiled, so none of this is part of building it, and threading it through
# the component's arguments only bought a `finalAttrs.finalPackage` self-reference and a list of
# argument names which had to be excluded from the derivation to keep its hash stable.
{
  buildSample,
  cuda-library-samples-src,
  cudaNamePrefix,
  lib,
  linkFarm,
  mkSampleManifestCheck,
  mkTest,
  mkTester,
}:
{
  # The component being exercised, taken as a named argument by the caller.
  component,
  # manifestPath :: Path
  # The component's checked-in manifest, as a path. It is read here rather than by the caller: the
  # parsed contents are wanted throughout this file and the path itself only by the drift check, so
  # taking both would be asking every component to pass the same file twice under two names, with
  # nothing to notice if the two ever stopped agreeing. They were declared as much as 169 lines
  # apart in some components, which is exactly the distance at which that goes unnoticed.
  #
  # Manifests are generated by `buildSample/manifest.py`; regenerate one with
  # `manifest.py generate --merge <manifest> <checkout>` and the `subtrees` its component declares,
  # which the drift check spells out in full when it fails. They are checked in because discovering
  # the projects at evaluation time would require import-from-derivation, and each is verified
  # against the checkout it describes by `mkSampleManifestCheck`.
  #
  # That regeneration establishes the set of projects and carries existing program lists forward; it
  # derives no program name, and emits an empty list for a project it has not seen before, failing
  # until someone fills it in. What fills it in is the project's own
  # `passthru.certifyPrograms`, which configures it with CMake and fails naming exactly which
  # executables this component's inputs cause to be built.
  manifestPath,
  # subtrees :: [String]
  # Which subtrees of CUDALibrarySamples this component covers -- the ones `manifest.py generate`
  # was handed when the manifest was written.
  #
  # Declared by the caller rather than read from `manifest.subtrees`, although the manifest check
  # requires the two to agree. That check is what notices a project upstream has *added*, and it can
  # only notice it in a subtree it was told to rescan; taking that list out of the manifest would
  # let the manifest choose its own scope, so dropping a subtree -- and with it every project
  # underneath -- would leave something which still "matched" because nothing went looking for what
  # was dropped. Coverage is narrowed here, in a hand-written file, or not at all.
  subtrees,
  # Extra build inputs every sample of this component needs beyond the component itself.
  buildInputs ? [ ],
  # sampleArgs :: Attrs
  # Extra `buildSample` arguments for one project, keyed by sampleRoot: its requirements
  # (`minCudaVersion`, `maxCudaVersion`, `minCudaCapability`), an upstream defect to patch around
  # (`postPatch`), a library only it links (`buildInputs`, `cmakeFlags`, `NIX_LDFLAGS`), or a
  # `meta.problems` entry recording that it cannot be built here at all.
  #
  # Keyed on sampleRoot rather than on the manifest key so a change to key derivation cannot silently
  # detach an override, and taken as a table rather than as a function so that its keys can be
  # checked against the manifest below. A key matching no project is a typo, and a typo is silent in
  # the worst way when it carries `minCudaCapability`: the sample still builds, the test loses its
  # `cuda-sm-<capability>` requirement, and it is scheduled onto a GPU which cannot run it.
  #
  # This is deliberately per-sample. The predecessor was a set of arguments merged into *every*
  # sample of the component, which meant cuSPARSE added the driver stub to a link line for
  # thirty-four projects to satisfy the one which links `-lcuda`, and -- because it was merged over
  # the generated arguments with `//` -- an override which mentioned `buildInputs` would have
  # dropped every input the component declared without saying so.
  sampleArgs ? { },
  # sampleArgsFor :: String -> Attrs
  # As above, for a rule which applies to a family of projects rather than to one -- every cuBLASLt
  # sample needs CUDA 12.8 -- and which therefore has no key to check against the manifest. Merged
  # with `sampleArgs` under the rules below, so that a family rule and a per-sample override cannot
  # silently displace one another.
  sampleArgsFor ? _: { },
  # testArgs :: { <sampleRoot> = { <program> = Attrs; }; }
  # Extra `mkTester` arguments for one executable: the `args` to invoke it with, the `dataFiles` it
  # opens by a relative path, the `workSubdir` those paths are relative to, the `expectedOutputs` it
  # must have written, and any `runtimeInputs` it needs on PATH.
  #
  # One argument here is not `mkTester`'s: `dataDir`, resolved below, which lets a project that
  # reads and writes through a single directory name that directory once instead of at every path.
  #
  # Nested by project and then by executable, rather than keyed by the tester's name, because that
  # is the shape the manifest can be checked against: a project which is not in the manifest and an
  # executable that project does not build are both caught here, and both are otherwise silent.
  # It has to reach an executable rather than a project because a project builds several and they do
  # not want the same invocation -- `cuDSS/simple_mgmn_mode` builds one program per communication
  # backend, and each is told the name and the layer library of its own.
  #
  # Distinct from `sampleArgs` above, which reaches `buildSample`: how a sample is compiled and how
  # it is invoked are different questions, and threading an invocation through the compile would
  # rebuild every sample whose arguments were corrected.
  testArgs ? { },
  src ? cuda-library-samples-src,
}:
let
  inherit (component) pname;

  manifest = lib.importJSON manifestPath;

  # Arguments derived from the manifest entry. An override which set one of these would detach the
  # sample from the entry it was generated from, so they are refused rather than merged.
  generatedArgNames = [
    "component"
    "src"
    "sampleRoot"
    "programs"
  ];

  # Overrides are merged into the generated arguments rather than layered over them, so that an
  # override can add to a list without having to know -- and restate -- what the component already
  # put there. Lists concatenate, attribute sets merge recursively (so `meta.problems` does not
  # displace `meta.homepage`), and the phase hooks append. Anything else is a genuine conflict and
  # throws: replacing a value silently is the failure mode this exists to prevent, so there is no
  # rule under which it can happen.
  mergeSampleArgs =
    context: lower: upper:
    lib.zipAttrsWith
      (
        name: values:
        if lib.length values == 1 then
          lib.head values
        else
          let
            lowerValue = lib.elemAt values 0;
            upperValue = lib.elemAt values 1;
            # Derivations are attribute sets, and merging two of them would produce something which is
            # neither.
            isMergeableAttrs = value: lib.isAttrs value && !lib.isDerivation value;
          in
          if lib.isList lowerValue && lib.isList upperValue then
            lowerValue ++ upperValue
          else if isMergeableAttrs lowerValue && isMergeableAttrs upperValue then
            mergeSampleArgs context lowerValue upperValue
          else if
            lib.isString lowerValue && lib.isString upperValue && lib.match "(pre|post)[A-Z].*" name != null
          then
            lowerValue + "\n" + upperValue
          else
            throw (
              "${pname}: ${context} sets ${name}, which is already set and cannot be merged; lists,"
              + " attribute sets and pre*/post* hooks are merged, and anything else would have to"
              + " replace a value it cannot see"
            )
      )
      [
        lower
        upper
      ];

  # A package which cannot be used here cannot be linked against here, and a sample which cannot be
  # built cannot be run, so the reasons have to reach the sample. Without them the sample reports
  # itself available while something it is built against refuses to evaluate, and every consumer
  # which filters on `meta.available` -- including the aggregate which compiles all of them -- takes
  # the throw instead of skipping the sample. Marking one component broken took down the whole
  # aggregate, including every component which was perfectly healthy.
  #
  # `buildSample` inherits `license` and `platforms` from the component, which covers a component
  # which is unfree or unsupported here. This covers the rest, and covers it for every package the
  # sample is built against rather than for the component alone -- cuSOLVER's samples link cuBLAS,
  # and cuDSS's multi-node sample links MPI and NCCL. The problems are renamed after the package
  # they came from and their messages prefixed with its name, rather than carried over verbatim, so
  # that the reader is told which package is in trouble instead of being shown a sample which claims
  # to be broken itself.
  problemsOfInputs =
    inputs:
    lib.foldl' (
      acc: input:
      acc
      // lib.mapAttrs' (
        name: problem:
        lib.nameValuePair "${lib.getName input}-${name}" (
          problem
          // {
            kind = problem.kind or name;
            message = "${input.name}, which this sample is built against, ${problem.message}";
          }
        )
      ) (input.meta.problems or { })
    ) { } inputs;

  # A project's path with its separators joined, for the places which cannot hold a `/`: attribute
  # names in the set of tests, and the derivation names built from them.
  #
  # Derived here rather than stored in the manifest, which is keyed by the path itself. Keeping both
  # meant every entry carried two spellings of one fact, and it let two projects collide onto one
  # key -- `a/b-c` and `a-b/c` both join to `a-b-c` -- which the manifest generator needed a check
  # of its own to catch. The collision is still possible in the names below and is still caught, by
  # the uniqueness assertion on `testerEntries`; what has gone is a second place for it to happen.
  sampleKeyOf = lib.replaceStrings [ "/" ] [ "-" ];

  sampleArgsOf =
    sampleRoot: programs:
    let
      generated = {
        inherit
          component
          programs
          sampleRoot
          src
          ;
        inherit buildInputs;
        passthru = {
          # The component, and the key naming this project, so that a consumer which collects
          # samples through the tests that run them can tell what it has without re-deriving the
          # key or assuming the project's basename is unique.
          inherit component;
          sampleKey = sampleKeyOf sampleRoot;
        };
        meta.homepage = "https://github.com/NVIDIA/CUDALibrarySamples/tree/master/${sampleRoot}";
      };
      override = mergeSampleArgs "the overrides for sample ${sampleRoot}" (sampleArgsFor sampleRoot) (
        sampleArgs.${sampleRoot} or { }
      );
      generatedOverridden = lib.intersectLists generatedArgNames (lib.attrNames override);
      merged = mergeSampleArgs "the override for sample ${sampleRoot}" generated override;
    in
    assert lib.assertMsg (generatedOverridden == [ ]) (
      "${pname}: the override for sample ${sampleRoot} may not set"
      + " ${lib.concatStringsSep ", " generatedOverridden}, which is derived from the manifest"
    );
    merged
    // {
      # Asked of the merged arguments rather than of `buildInputs` above, so that an input added by
      # an override for one project is asked about too. A problem the override states itself wins:
      # it was written about this sample, while these are inherited.
      meta = merged.meta // {
        problems =
          problemsOfInputs ([ component ] ++ merged.buildInputs ++ merged.nativeBuildInputs or [ ])
          // merged.meta.problems or { };
      };
    };

  samplePrograms = lib.mapAttrs (
    sampleRoot: programs: buildSample (sampleArgsOf sampleRoot programs)
  ) manifest.samples;

  # Testers are keyed by project and executable rather than by executable alone. A project may build
  # several -- `cuBLAS/Level-1/dot` builds two -- and different projects may build executables of the
  # same name: `cuBLAS/Emulation/bf16x9_gemmEx` and `cuBLAS/Extensions/GemmEx` both build
  # `cublas_GemmEx_example`. Keying on the executable alone would silently drop one of each such
  # pair through listToAttrs.
  testerEntries = lib.concatMap (
    sampleRoot:
    map (program: {
      name = "${sampleKeyOf sampleRoot}-${program}";
      inherit sampleRoot program;
    }) manifest.samples.${sampleRoot}
  ) (lib.attrNames manifest.samples);

  # Arguments derived from the manifest entry, as `generatedArgNames` is for `buildSample`. `cmdArgs`
  # is among them because it names the executable: an override which set it could point the tester
  # at a different program while the test kept the name of this one.
  generatedTesterArgNames = [
    "component"
    "name"
    "sample"
    "cmdArgs"
  ];

  testerArgsOf =
    entry:
    let
      inherit (entry) sampleRoot;
      override = testArgs.${sampleRoot}.${entry.program} or { };
      generatedOverridden = lib.intersectLists generatedTesterArgNames (lib.attrNames override);

      # Several of these projects take no path on the command line at all: each opens its inputs
      # through a directory constant compiled into it -- upstream's `images/` -- and writes its
      # results back into the same place. Both sides of such a run sit under one directory, so
      # `dataDir` names it once and it is applied here: `dataFiles` given as a list of file names
      # stages each from the project's own copy of that directory in the checkout, and every
      # `expectedOutputs` entry is resolved under it too.
      #
      # Repeating the directory at each path is how the two sides come to disagree about where the
      # program is looking, and neither the build nor the run reports that: a sample which opens
      # nothing still exits 0, which is the failure `expectedOutputs` exists to catch and would
      # itself be looking in the wrong place.
      underDataDir = path: if override ? dataDir then "${override.dataDir}/${path}" else path;
      resolvedPaths = {
        dataFiles =
          let
            dataFiles = override.dataFiles or { };
          in
          if lib.isList dataFiles then
            lib.genAttrs (map underDataDir dataFiles) (path: "${src}/${sampleRoot}/${path}")
          else
            dataFiles;
        expectedOutputs = map underDataDir (override.expectedOutputs or [ ]);
      };
    in
    assert lib.assertMsg (generatedOverridden == [ ]) (
      "${pname}: the test arguments for ${sampleRoot} ${entry.program} may not set"
      + " ${lib.concatStringsSep ", " generatedOverridden}; the invocation is built from the"
      + " manifest, and `args` is how a program is given arguments"
    );
    {
      inherit component;
      inherit (entry) name;
      sample = samplePrograms.${entry.sampleRoot};
      # A program is invoked with its own name and then whatever it was given, so an override cannot
      # accidentally lose the executable it is supposed to run.
      cmdArgs = [ entry.program ] ++ override.args or [ ];
    }
    // lib.removeAttrs override [
      "args"
      "dataDir"
    ]
    // resolvedPaths;

  testers = lib.listToAttrs (
    map (entry: {
      inherit (entry) name;
      value = mkTester (testerArgsOf entry);
    }) testerEntries
  );

  # Tests are derived from testers rather than defined alongside them so that the two cannot drift,
  # and are a separate derivation from the tester so the same executable can be run outside the
  # sandbox -- under nixGL, on a non-NixOS host -- without rebuilding it.
  tests = lib.mapAttrs (_: tester: mkTest { inherit tester; }) testers;

  # Both checks are checks on the manifest which lists these very projects, so they belong among the
  # tests rather than beside them, and their names are reserved: a project called `manifest` building
  # a program called `check` would otherwise silently displace one.
  checkNames = {
    manifest = mkSampleManifestCheck {
      inherit component src subtrees;
      manifest = manifestPath;
    };
    programs = programsCheck;
  };

  # Every project's declared program list, put to CMake.
  #
  # `buildSample`'s installPhase already compares a declared list against the executables it
  # produced, which is the stronger check -- but it runs only where the project compiles, against
  # the components available on that builder. This compiles nothing, so it runs for every project
  # this component has, including the ones which cannot be built at all. That is not a marginal
  # gain: both of the wrong program lists this tree has carried were nvCOMP's, whose projects do
  # not compile against the nvCOMP shipped here, and nothing had ever looked at them.
  #
  # Aggregated rather than left as a per-sample attribute so that it is one thing to build and one
  # job to watch, in the same shape and for the same reasons as `tests/sample-manifests.nix`.
  programsCheck =
    (linkFarm "${cudaNamePrefix}-${pname}-sample-programs" (
      lib.mapAttrs' (
        sampleRoot: sample: lib.nameValuePair (sampleKeyOf sampleRoot) sample.certifyPrograms
      ) samplePrograms
    )).overrideAttrs
      (prevAttrs: {
        meta = prevAttrs.meta or { } // {
          description = "Check ${pname}'s sample program lists against CMake's own answer";
          # Taken from the component for the reason `mkSampleManifestCheck` gives beside its own:
          # without it this contributes a job on every platform the package set is evaluated for,
          # including those where the component has no release and there is nothing to configure
          # against.
          inherit (component.meta) platforms;
          license = src.meta.license;
          teams = [ lib.teams.cuda ];
        };
      });

  # `sampleArgs`, `testArgs` and the manifest are all keyed by sampleRoot, so checking an override
  # against the projects which exist is a comparison of attribute names, and checking the inner keys
  # of `testArgs` is a lookup in the manifest itself. A `testArgs` entry naming a program the project
  # does not build is discarded in silence, and what is discarded with it is the input data or the
  # arguments without which the program fails -- or worse, appears to succeed while doing nothing.
  sampleRoots = lib.attrNames manifest.samples;
  unknownSampleArgs = lib.subtractLists sampleRoots (lib.attrNames sampleArgs);
  unknownTestArgs = lib.subtractLists sampleRoots (lib.attrNames testArgs);
  unknownTestArgPrograms = lib.concatMap (
    sampleRoot:
    map (program: "${sampleRoot} ${program}") (
      lib.subtractLists manifest.samples.${sampleRoot} (lib.attrNames testArgs.${sampleRoot})
    )
  ) (lib.intersectLists sampleRoots (lib.attrNames testArgs));
  programlessSamples = lib.attrNames (
    lib.filterAttrs (_: programs: programs == [ ]) manifest.samples
  );

  # The tests are the only route to a sample -- `tests/samples-built.nix` reaches one through
  # `test.tester.sample` and then asks it which component it belongs to and which project it was
  # built from -- and those two answers travel in the `passthru` handed to `buildSample` above.
  # `buildSample` decides what becomes of that: it drops `component` from the derivation arguments
  # and builds a `passthru` of its own, into which the one it is given is merged. Nothing but this
  # states that it must keep doing so, and a consumer finding `sampleKey` missing would learn only
  # that it is missing, not who was supposed to set it.
  passthruUnforwarded = lib.attrNames (
    lib.filterAttrs (
      sampleRoot: sample:
      !(sample ? component && sample ? sampleKey && sample.sampleKey == sampleKeyOf sampleRoot)
    ) samplePrograms
  );
in
assert lib.assertMsg (
  manifest.samples != { }
) "${pname}: the sample manifest describes no projects, so there would be nothing to test";
assert lib.assertMsg (unknownSampleArgs == [ ]) (
  "${pname}: sampleArgs is keyed by"
  + " ${lib.concatStringsSep ", " unknownSampleArgs}, which"
  + " ${if lib.length unknownSampleArgs == 1 then "is not a sampleRoot" else "are not sampleRoots"}"
  + " in the manifest; an override keyed on a project which does not exist is discarded in silence"
);
assert lib.assertMsg (unknownTestArgs == [ ]) (
  "${pname}: testArgs is keyed by"
  + " ${lib.concatStringsSep ", " unknownTestArgs}, which"
  + " ${if lib.length unknownTestArgs == 1 then "is not a sampleRoot" else "are not sampleRoots"}"
  + " in the manifest; test arguments keyed on a project which does not exist are discarded in"
  + " silence"
);
assert lib.assertMsg (unknownTestArgPrograms == [ ]) (
  "${pname}: testArgs names ${lib.concatStringsSep ", " unknownTestArgPrograms}, which the manifest"
  + " does not declare among that project's programs; test arguments for an executable which is not"
  + " built are discarded in silence"
);
# A project which builds nothing is a manifest error, and it is the tests which carry the samples:
# a project with no programs would have no tester, and its sample would be reachable from nothing.
assert lib.assertMsg (programlessSamples == [ ]) (
  "${pname}: the manifest declares no programs for ${lib.concatStringsSep ", " programlessSamples},"
  + " so nothing would run them"
);
assert lib.assertMsg (
  lib.length (lib.unique (map (entry: entry.name) testerEntries)) == lib.length testerEntries
) "${pname}: sample tester keys are not unique";
assert lib.assertMsg (lib.intersectLists (lib.attrNames checkNames) (lib.attrNames tests) == [ ]) (
  "${pname}: a project produced tests named"
  + " ${lib.concatStringsSep ", " (lib.intersectLists (lib.attrNames checkNames) (lib.attrNames tests))},"
  + " which the manifest and programs checks reserve"
);
assert lib.assertMsg (passthruUnforwarded == [ ]) (
  "${pname}: the samples for ${lib.concatStringsSep ", " passthruUnforwarded} do not carry the"
  + " component and sampleKey this file puts in the passthru it hands to buildSample; buildSample"
  + " must merge the passthru it is given, because that is how a test reaches the sample it runs"
);
lib.recurseIntoAttrs (tests // checkNames)
