let
  instantiate = import ./default.nix;

  reconstructiblePlatform =
    platform:
    if
      builtins.isAttrs platform
      && platform ? _withoutFunctions
      && builtins.isAttrs platform._withoutFunctions
      && platform._withoutFunctions ? parsed
      && builtins.isAttrs platform._withoutFunctions.parsed
      && platform._withoutFunctions.parsed ? abi
      && builtins.isAttrs platform._withoutFunctions.parsed.abi
    then
      platform._withoutFunctions
      // {
        parsed = platform._withoutFunctions.parsed // {
          abi = platform._withoutFunctions.parsed.abi // {
            # ABI assertions are regenerated by lib.systems.elaborate.
            assertions = [ ];
          };
        };
      }
    else
      platform;

  relevantArgs =
    args:
    let
      # Preserve whether an argument was supplied.  The raw entrypoint relies
      # on omitted defaults being re-inferred in recursive instantiations.
      supplied = builtins.intersectAttrs {
        localSystem = null;
        crossSystem = null;
        config = null;
        __allowFileset = null;
        overlays = null;
        crossOverlays = null;
        stdenvStages = null;
      } args;
    in
    supplied
    // {
      localSystem = reconstructiblePlatform supplied.localSystem;
    }
    // (
      if supplied ? crossSystem && supplied.crossSystem != null then
        { crossSystem = reconstructiblePlatform supplied.crossSystem; }
      else
        { }
    );

  memoizedInstantiate = import ./memoize.nix {
    f = instantiate;
    fallbackOnUnsupported = true;
  };
in
args: memoizedInstantiate (relevantArgs args)
